import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const Index = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.page}>
				<h1>Simple Page Next JS</h1>
				<Link href='/complex-page'>Go to useRouter Page</Link>
			</div>
		</>
	);
};

export default Index;
