import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useRouter } from 'next/router';

const Index = () => {
	const router = useRouter();
	const path = router.asPath;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.page}>
				<h1>UseRouter Complex Page Next JS</h1>
				<p>{path}</p>
			</div>
		</>
	);
};

export default Index;
